apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"prometheus-sample:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"prometheus-sample\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2022-02-22T12:57:50Z"
    generation: 12
    labels:
      app: prometheus-sample
      app.kubernetes.io/component: prometheus-sample
      app.kubernetes.io/instance: prometheus-sample
    name: prometheus-sample
    namespace: my-test
    resourceVersion: "537245521"
    uid: b1506184-7d59-42ac-9ffd-23bb4f9c8d7e
  spec:
    progressDeadlineSeconds: 600
    replicas: 2
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: prometheus-sample
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: prometheus-sample
      spec:
        containers:
        - env:
          - name: APP_FILE
            value: sample-prom.py
          image: image-registry.openshift-image-registry.svc:5000/my-test/prometheus-sample@sha256:48438cb8e46a64f89cb3efc4963cea436e982a2a52a4c48316da9ded4747d029
          imagePullPolicy: IfNotPresent
          name: prometheus-sample
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 2
    conditions:
    - lastTransitionTime: "2022-02-22T12:57:50Z"
      lastUpdateTime: "2022-02-22T13:14:00Z"
      message: ReplicaSet "prometheus-sample-685f56db8d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2022-06-20T11:04:37Z"
      lastUpdateTime: "2022-06-20T11:04:37Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 12
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
